services:
  mongodb:
    image: mongo:7
    container_name: main-service-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=main-service

volumes:
  mongodb_data:
